---
language: ruby

rvm:
  - 2.4.9
  - 2.5.7

env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.8.0"
    - PUPPET_GEM_VERSION="~> 3" FUTURE_PARSER="yes"
      #- PUPPET_GEM_VERSION="~> 4.0.0"
      #- PUPPET_GEM_VERSION="~> 4.1.0"
      #- PUPPET_GEM_VERSION="~> 4.2.0"
      #- PUPPET_GEM_VERSION="~> 4.3.0"
      #- PUPPET_GEM_VERSION="~> 4.4.0"
      #- PUPPET_GEM_VERSION="~> 4.5.0"
      #- PUPPET_GEM_VERSION="~> 4.6.0"
      #- PUPPET_GEM_VERSION="~> 4.7.0"
      #- PUPPET_GEM_VERSION="~> 4.8.0"
    - PUPPET_GEM_VERSION="~> 4"

sudo: false

before_install:
  - 'gem update --system'
  - 'gem update bundler'

before_script:
  # Syck is mentioned in this file, but obsolete
  - 'sed -i -e /require.*syck_node_monkeypatch/d ~/.rvm/gems/ruby-*/gems/puppet-*/lib/puppet/vendor/safe_yaml/lib/safe_yaml.rb || true'

script:
  - 'SPEC_OPTS="--format documentation" bundle exec rake validate lint spec'

matrix:
  fast_finish: true
  #exclude:
  #  - rvm: 2.3.1
  #    env: PUPPET_GEM_VERSION="~> 3.8.0"
  #  - rvm: 2.3.1
  #    env: PUPPET_GEM_VERSION="~> 3" FUTURE_PARSER="yes"

notifications:
  email: false
